# Generated by Django 4.2.1 on 2023-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('buying_date', models.DateField()),
                ('carColor', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('carEmail', models.EmailField(max_length=254)),
                ('carImage', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=89)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
