# Generated by Django 4.2.1 on 2023-08-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('program_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('adp', 'ADP')], max_length=10)),
                ('name_of_program', models.CharField(max_length=100)),
                ('reason_to_join', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
