# Generated by Django 4.2.1 on 2023-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_applicant_delete_car_delete_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('cnic', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
