# Generated by Django 4.2.1 on 2023-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_universityemployee_delete_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityemployee',
            name='name_of_program',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='program_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='reason_to_join',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='universityemployee',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universityemployee',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universityemployee',
            name='state_name',
            field=models.CharField(max_length=100),
        ),
    ]
