# Generated by Django 4.2.1 on 2023-08-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_universityemployee_name_of_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityemployee',
            name='degree_level',
            field=models.CharField(choices=[('Matric', 'Matric'), ('O-Levels', 'O-Levels'), ('MYP Program', 'MYP Program')], default='Matric', max_length=20),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='ending_year',
            field=models.PositiveIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='matric_subject_group',
            field=models.CharField(choices=[('Science', 'Science'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts')], default='Science', max_length=20),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='obtained_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='school_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='starting_year',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
