# Generated by Django 4.2.1 on 2023-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_universityemployee_degree_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityemployee',
            name='earn_while_you_learn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='end_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='institute_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='internship_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='kin_already_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='merit_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='part_one_obtained_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='part_two_obtained_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='start_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='universityemployee',
            name='subject_group',
            field=models.CharField(choices=[('Pre-Medical', 'Pre-Medical'), ('Pre-Engineering', 'Pre-Engineering'), ('Arts', 'Arts'), ('Intermediate with CS (ICS)', 'Intermediate with CS (ICS)'), ('I.com', 'I.com'), ('DAE Program', 'DAE Program')], default='Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='universityemployee',
            name='degree_level',
            field=models.CharField(max_length=50),
        ),
    ]
