# Generated by Django 4.2.1 on 2023-08-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_crud_delete_universityemployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='father_name',
        ),
    ]
