# Generated by Django 4.2.1 on 2023-08-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curd',
            new_name='Crud',
        ),
    ]
