# Generated by Django 4.2.1 on 2023-08-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_curd_crud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='father_name',
        ),
    ]
