# Generated by Django 4.2.1 on 2023-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teams_player_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(to='app.team'),
        ),
    ]
