# Generated by Django 4.2.1 on 2023-06-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_expenses_feedback_payroll_training_task_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='over_timepay',
            new_name='overtime_pay',
        ),
    ]
