# Generated by Django 4.2.3 on 2023-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('cnic', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('program_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('adp', 'ADP')], max_length=10)),
                ('name_of_program', models.CharField(max_length=100)),
                ('reason_to_join', models.CharField(choices=[('Additional Skill', 'Additional Skill'), ('Passive Income', 'Passive Income'), ('Career Path', 'Career Path'), ('Increased Income', 'Increased Income'), ('Acquire Degree', 'Acquire Degree'), ('Acquire Knowledge', 'Acquire Knowledge')], max_length=100)),
                ('matric_degree_level', models.CharField(max_length=15)),
                ('matric_subject_group', models.CharField(max_length=30)),
                ('o_level_subject_group_1', models.CharField(blank=True, max_length=100, null=True)),
                ('o_level_subject_group_2', models.CharField(blank=True, max_length=100, null=True)),
                ('o_level_subject_group_3', models.CharField(blank=True, max_length=100, null=True)),
                ('o_level_subject_group_4', models.CharField(blank=True, max_length=100, null=True)),
                ('o_level_subject_group_5', models.CharField(blank=True, max_length=100, null=True)),
                ('o_level_subject_group_english', models.BooleanField(default=False)),
                ('o_level_subject_group_urdu', models.BooleanField(default=False)),
                ('o_level_subject_group_pak', models.BooleanField(default=False)),
                ('o_level_subject_group_islamiyat', models.BooleanField(default=False)),
                ('matric_name_of_institute', models.CharField(max_length=100)),
                ('matric_degree_starting_date', models.PositiveIntegerField()),
                ('matric_degree_ending_date', models.PositiveIntegerField()),
                ('matric_part_one_obtained_marks', models.PositiveIntegerField()),
                ('matric_part_one_total_marks', models.PositiveIntegerField()),
            ],
        ),
    ]
