# Generated by Django 4.2.1 on 2023-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='scholarship_type_earn',
            field=models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='scholarship_type_intern',
            field=models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='scholarship_type_kin',
            field=models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='scholarship_type_merit',
            field=models.BooleanField(default=False),
        ),
    ]
