# Generated by Django 4.2.1 on 2023-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_applicant_scholarship_type_earn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('highest_education', models.CharField(choices=[('Matriculation', 'Matriculation'), ('Intermediate', 'Intermediate'), ('Bachelor', 'Bachelor')], max_length=50)),
                ('matric_name_of_institute', models.CharField(max_length=255)),
                ('matric_starting_date', models.PositiveIntegerField()),
                ('matric_ending_date', models.PositiveIntegerField()),
                ('matric_obtained_marks', models.PositiveIntegerField()),
                ('matric_total_marks', models.PositiveIntegerField()),
                ('inter_name_of_institute', models.CharField(max_length=255)),
                ('inter_degree_level', models.CharField(max_length=20)),
                ('inter_subject_group', models.CharField(max_length=50)),
                ('inter_degree_starting_date', models.PositiveIntegerField()),
                ('inter_degree_ending_date', models.PositiveIntegerField()),
                ('inter_part_one_obtained_marks', models.PositiveIntegerField()),
                ('inter_part_two_obtained_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('a_level_inter_Subject_Group_1', models.CharField(blank=True, max_length=100, null=True)),
                ('a_level_inter_Subject_Group_2', models.CharField(blank=True, max_length=100, null=True)),
                ('a_level_inter_Subject_Group_3', models.CharField(blank=True, max_length=100, null=True)),
                ('a_level_inter_Subject_Group_4', models.CharField(blank=True, max_length=100, null=True)),
                ('a_level_inter_Subject_Group_5', models.CharField(blank=True, max_length=100, null=True)),
                ('scholarship_type_merit', models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20)),
                ('scholarship_type_intern', models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20)),
                ('scholarship_type_earn', models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20)),
                ('scholarship_type_kin', models.CharField(choices=[('Merit-100', '100% Merit Based Scholarship'), ('Internee-50', '50% Internee Scholarship'), ('Earn & Pay-50', '50% Earn & Pay Scholarship'), ('Kinship-10', '10% Kinship Scholarship')], default='No', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
