# Generated by Django 4.2.1 on 2023-07-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_application_delete_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('cnic_or_bform_number', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postal_address', models.TextField()),
                ('matric_level', models.CharField(max_length=50)),
                ('matric_board', models.CharField(max_length=100)),
                ('matric_institute_name', models.CharField(max_length=100)),
                ('matric_starting_year', models.PositiveIntegerField()),
                ('matric_ending_year', models.PositiveIntegerField()),
                ('matric_obtained_marks', models.PositiveIntegerField()),
                ('inter_level', models.CharField(max_length=50)),
                ('inter_subject_group', models.CharField(max_length=100)),
                ('inter_institute_name', models.CharField(max_length=100)),
                ('inter_starting_year', models.PositiveIntegerField()),
                ('inter_ending_year', models.PositiveIntegerField()),
                ('inter_part_one_obtained_marks', models.PositiveIntegerField()),
                ('inter_part_two_obtained_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('scholarship_type_merit', models.BooleanField(default=False)),
                ('scholarship_type_intern', models.BooleanField(default=False)),
                ('scholarship_type_earn', models.BooleanField(default=False)),
                ('scholarship_type_kin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
