# Generated by Django 4.2.1 on 2023-08-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_applicant_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('cnic', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('state_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('program_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('adp', 'ADP')], max_length=10)),
                ('name_of_program', models.CharField(max_length=100)),
                ('reason_to_join', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('starting_year', models.PositiveIntegerField()),
                ('ending_year', models.PositiveIntegerField()),
                ('obtained_marks', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formapp.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('Inter', 'Intermediate'), ('A-Levels', 'A-Levels'), ('DP Program', 'DP Program')], max_length=20)),
                ('subject_group', models.CharField(choices=[('Pre-Medical', 'Pre Medical'), ('Pre-Engineering', 'Pre Engineering'), ('Art & Humanities', 'Art & Humanities'), ('Intermediate with CS (ICS)', 'Intermediate with CS (ICS)'), ('I.Com', 'I.Com'), ('DAE Program', 'DAE Program')], max_length=50)),
                ('institute_name', models.CharField(max_length=200)),
                ('starting_year', models.PositiveIntegerField()),
                ('ending_year', models.PositiveIntegerField()),
                ('part_one_obtained_marks', models.PositiveIntegerField()),
                ('part_two_obtained_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formapp.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_based', models.BooleanField(default=False)),
                ('internship_based', models.BooleanField(default=False)),
                ('earn_while_you_learn', models.BooleanField(default=False)),
                ('kin_already_studying', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formapp.applicants')),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
